import { db, schema } from "../db/index.ts";
import { eq } from "drizzle-orm";

/**
 * Built-in default prompts per agent, used as the starting inputTemplate
 * when an agent node is added to a flow. Extracted from the original
 * hardcoded values in flow-defaults.ts.
 */
export const DEFAULT_AGENT_PROMPTS: Record<string, string> = {
  research:
    "Analyze user request and identify requirements. Original request: {{userMessage}}",
  architect:
    "Design the component architecture and test plan based on the research agent's requirements (provided in Previous Agent Outputs). Original request: {{userMessage}}",
  "frontend-dev":
    "Implement the React components defined in the architect's plan (provided in Previous Agent Outputs). A test plan is included in the architect's output — write test files alongside your components following the plan. Original request: {{userMessage}}",
  "backend-dev":
    "Implement the backend API routes and server logic defined in the architect's plan (provided in Previous Agent Outputs). Original request: {{userMessage}}",
  styling:
    "Apply design polish to the components created by frontend-dev, using the research requirements for design intent (both provided in Previous Agent Outputs). Original request: {{userMessage}}",
  "code-review":
    "Review and fix all code generated by dev and styling agents (provided in Previous Agent Outputs). Original request: {{userMessage}}",
  security:
    "Security review all code generated by the dev agents (provided in Previous Agent Outputs). Original request: {{userMessage}}",
  qa:
    "Validate the implementation against the research requirements (both provided in Previous Agent Outputs). Original request: {{userMessage}}",
  "orchestrator:question": "## Question\n{{userMessage}}",
};

/**
 * Load the effective default prompt for an agent:
 * 1. DB override (agent.{name}.defaultPrompt in app_settings)
 * 2. Built-in default from DEFAULT_AGENT_PROMPTS
 * 3. Generic fallback
 */
export function loadDefaultPrompt(agentName: string): string {
  const row = db
    .select()
    .from(schema.appSettings)
    .where(eq(schema.appSettings.key, `agent.${agentName}.defaultPrompt`))
    .get();
  if (row?.value) return row.value;
  return DEFAULT_AGENT_PROMPTS[agentName] ?? "{{userMessage}}";
}

/**
 * Check whether the agent has a custom (user-overridden) default prompt.
 */
export function isDefaultPromptCustom(agentName: string): boolean {
  const row = db
    .select()
    .from(schema.appSettings)
    .where(eq(schema.appSettings.key, `agent.${agentName}.defaultPrompt`))
    .get();
  return !!row;
}
